"""No-leak RF residual corrector for the thermal-mass physics model.

The RF is trained on fit-split residuals only:

    residual = actual - thermal_mass_physics_prediction

At evaluation time, the RF sees only exogenous/control inputs and states
generated by the physics model. It does not receive measured room temperature,
electric power or gas consumption from the evaluation horizon.
"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import replace
from pathlib import Path

import numpy as np
import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error

sys.path.insert(0, str(Path(__file__).parent))
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

import thermal_mass_physics_model as tm  # noqa: E402
from compare_ensemble import _build_aligned_index, _load_raw_df  # noqa: E402
from emhass.thermal.forecast_gridsearch import (  # noqa: E402
    SearchOptions,
    _prepare_features,
    create_sequences,
    split_sequences,
)


def _metrics(true: np.ndarray, pred: np.ndarray) -> dict[str, float]:
    err = np.asarray(pred, dtype=float) - np.asarray(true, dtype=float)
    return {
        "rmse": float(np.sqrt(mean_squared_error(true, pred))),
        "mae": float(mean_absolute_error(true, pred)),
        "bias": float(np.mean(err)),
    }


def _slice(raw_df: pd.DataFrame, ts: np.ndarray) -> pd.DataFrame:
    return raw_df.reindex(pd.DatetimeIndex(ts)).dropna(how="all")


def _simulate_segmented_full(
    inputs: tm.ThermalInputs,
    params: np.ndarray,
    *,
    dt_h: float,
    segment_len: int,
) -> tm.SimResult:
    rooms: list[np.ndarray] = []
    air_before: list[np.ndarray] = []
    mass: list[np.ndarray] = []
    q_emit: list[np.ndarray] = []
    q_solar: list[np.ndarray] = []
    loss_coeff: list[np.ndarray] = []

    for start in range(0, len(inputs.room), segment_len):
        stop = min(len(inputs.room), start + segment_len)
        sub = replace(
            inputs,
            index=inputs.index[start:stop],
            room=inputs.room[start:stop],
            electric=inputs.electric[start:stop],
            gas=inputs.gas[start:stop],
            duty=inputs.duty[start:stop],
            supply=inputs.supply[start:stop],
            outdoor=inputs.outdoor[start:stop],
            wind_speed=inputs.wind_speed[start:stop],
            wind_sin=inputs.wind_sin[start:stop],
            wind_cos=inputs.wind_cos[start:stop],
            q_solar=inputs.q_solar[start:stop],
            sun_alt_sin=inputs.sun_alt_sin[start:stop],
            sun_alt_cos=inputs.sun_alt_cos[start:stop],
            sun_az_sin=inputs.sun_az_sin[start:stop],
            sun_az_cos=inputs.sun_az_cos[start:stop],
            heatpump_duty=inputs.heatpump_duty[start:stop],
        )
        initial_air = float(inputs.room[max(0, start - 1)])
        initial_q_emit = float(
            inputs.duty[max(0, start - 1)]
            * max(inputs.supply[max(0, start - 1)] - initial_air, 0.0)
        )
        sim = tm._simulate_open_loop(
            sub,
            params,
            dt_h=dt_h,
            initial_air=initial_air,
            initial_mass=initial_air,
            initial_q_emit=initial_q_emit,
        )
        rooms.append(sim.room)
        air_before.append(sim.air_before)
        mass.append(sim.mass)
        q_emit.append(sim.q_emit)
        q_solar.append(sim.q_solar)
        loss_coeff.append(sim.loss_coeff)

    return tm.SimResult(
        room=np.concatenate(rooms),
        air_before=np.concatenate(air_before),
        mass=np.concatenate(mass),
        q_emit=np.concatenate(q_emit),
        q_solar=np.concatenate(q_solar),
        loss_coeff=np.concatenate(loss_coeff),
    )


def _prepare_inputs(df: pd.DataFrame, config: dict) -> tm.ThermalInputs:
    return tm._prepare_inputs(
        df,
        latitude=float(config["latitude"]),
        longitude=float(config["longitude"]),
        facade_azimuth_deg=float(config["facade_azimuth_deg"]),
        facade_tilt_deg=float(config["facade_tilt_deg"]),
        solar_horizontal_weight=float(config["solar_horizontal_weight"]),
        solar_facade_weight=float(config["solar_facade_weight"]),
    )


def _residual_features(
    inputs: tm.ThermalInputs,
    sim: tm.SimResult,
    *,
    base_electric: np.ndarray,
    base_gas: np.ndarray,
) -> pd.DataFrame:
    index = pd.DatetimeIndex(inputs.index)
    local = index.tz_convert("Europe/Amsterdam") if index.tz is not None else index.tz_localize("UTC").tz_convert("Europe/Amsterdam")
    hour = local.hour.to_numpy(dtype=float) + local.minute.to_numpy(dtype=float) / 60.0
    hour_rad = 2.0 * np.pi * hour / 24.0

    delta_env = sim.air_before - inputs.outdoor
    supply_delta = np.clip(inputs.supply - sim.air_before, 0.0, None)
    lift = np.clip(inputs.supply - inputs.outdoor, 0.0, None)

    return pd.DataFrame(
        {
            "physics_room": sim.room,
            "physics_air_before": sim.air_before,
            "physics_t_mass": sim.mass,
            "physics_q_emit": sim.q_emit,
            "physics_loss_coeff": sim.loss_coeff,
            "physics_electric": base_electric,
            "physics_gas": base_gas,
            "heatpump_duty": inputs.heatpump_duty,
            "supply_temp": inputs.supply,
            "outdoor_temp": inputs.outdoor,
            "supply_delta": supply_delta,
            "lift": lift,
            "delta_env": delta_env,
            "wind_speed": inputs.wind_speed,
            "wind_sin": inputs.wind_sin,
            "wind_cos": inputs.wind_cos,
            "wind_loss": inputs.wind_speed * delta_env,
            "q_solar": inputs.q_solar,
            "sun_alt_sin": inputs.sun_alt_sin,
            "sun_alt_cos": inputs.sun_alt_cos,
            "sun_az_sin": inputs.sun_az_sin,
            "sun_az_cos": inputs.sun_az_cos,
            "hour_sin": np.sin(hour_rad),
            "hour_cos": np.cos(hour_rad),
        },
        index=index,
    ).replace([np.inf, -np.inf], np.nan).ffill().fillna(0.0)


def _fit_rf(X: pd.DataFrame, residual: np.ndarray, *, seed: int, n_estimators: int, min_samples_leaf: int) -> RandomForestRegressor:
    model = RandomForestRegressor(
        n_estimators=n_estimators,
        min_samples_leaf=min_samples_leaf,
        random_state=seed,
        n_jobs=-1,
    )
    model.fit(X.to_numpy(dtype=float), residual)
    return model


def _plot(pred_df: pd.DataFrame, metrics: dict[str, dict[str, dict[str, float]]], output_path: Path) -> None:
    df = pred_df.copy()
    df["timestamp"] = pd.to_datetime(df["timestamp"], utc=True)
    df = df.set_index("timestamp").sort_index()
    x = df.index.tz_convert("Europe/Amsterdam")

    fig = make_subplots(
        rows=4,
        cols=1,
        shared_xaxes=True,
        vertical_spacing=0.045,
        specs=[[{}], [{}], [{}], [{"secondary_y": True}]],
        subplot_titles=(
            "Room temperature",
            "Room temperature error",
            "Electric power",
            "Gas consumption and heatpump duty",
        ),
    )
    fig.add_trace(go.Scatter(x=x, y=df["true_room_temp"], mode="lines", name="Actual room", line=dict(color="#111827", width=2.4)), row=1, col=1)
    fig.add_trace(go.Scatter(x=x, y=df["physics_room_temp"], mode="lines", name="ThermalMassPhysics", line=dict(color="#0f766e", width=1.6, dash="dot")), row=1, col=1)
    fig.add_trace(go.Scatter(x=x, y=df["residual_rf_room_temp"], mode="lines", name="Physics + residual RF", line=dict(color="#2563eb", width=2.0)), row=1, col=1)
    fig.add_hline(y=0, line_width=1, line_color="#6b7280", row=2, col=1)
    fig.add_trace(go.Scatter(x=x, y=df["physics_room_temp"] - df["true_room_temp"], mode="lines", name="Physics error", line=dict(color="#0f766e", width=1.2), showlegend=False), row=2, col=1)
    fig.add_trace(go.Scatter(x=x, y=df["residual_rf_room_temp"] - df["true_room_temp"], mode="lines", name="Residual RF error", line=dict(color="#2563eb", width=1.4), showlegend=False), row=2, col=1)
    fig.add_trace(go.Scatter(x=x, y=df["true_electric_power"], mode="lines", name="Actual electric", line=dict(color="#111827", width=1.2)), row=3, col=1)
    fig.add_trace(go.Scatter(x=x, y=df["physics_electric_power"], mode="lines", name="Physics electric", line=dict(color="#0f766e", width=1.0, dash="dot")), row=3, col=1)
    fig.add_trace(go.Scatter(x=x, y=df["residual_rf_electric_power"], mode="lines", name="Residual RF electric", line=dict(color="#2563eb", width=1.2)), row=3, col=1)
    fig.add_trace(go.Scatter(x=x, y=df["true_gas_consumption"], mode="lines", name="Actual gas", line=dict(color="#111827", width=1.2)), row=4, col=1, secondary_y=False)
    fig.add_trace(go.Scatter(x=x, y=df["residual_rf_gas_consumption"], mode="lines", name="Residual RF gas", line=dict(color="#2563eb", width=1.1)), row=4, col=1, secondary_y=False)
    fig.add_trace(go.Scatter(x=x, y=df["heatpump_duty"], mode="lines", name="Heatpump duty", line=dict(color="#64748b", width=1.0)), row=4, col=1, secondary_y=True)

    summary = "<br>".join(
        f"{model} {target}: MAE {vals['mae']:.3f}, RMSE {vals['rmse']:.3f}, bias {vals['bias']:+.3f}"
        for model, by_target in metrics.items()
        for target, vals in by_target.items()
        if target == "room_temp"
    )
    fig.add_annotation(
        text=summary,
        xref="paper",
        yref="paper",
        x=0.01,
        y=0.995,
        showarrow=False,
        align="left",
        bgcolor="rgba(255,255,255,0.88)",
        bordercolor="rgba(0,0,0,0.12)",
        borderwidth=1,
        font=dict(size=11),
    )
    fig.update_layout(
        title="Thermal-mass physics + no-leak residual RF",
        template="plotly_white",
        height=1200,
        width=1550,
        hovermode="x unified",
        legend=dict(orientation="h", yanchor="bottom", y=1.01, xanchor="left", x=0),
    )
    fig.update_yaxes(title_text="degC", row=1, col=1)
    fig.update_yaxes(title_text="degC error", row=2, col=1)
    fig.update_yaxes(title_text="W", row=3, col=1)
    fig.update_yaxes(title_text="m3/interval", row=4, col=1, secondary_y=False)
    fig.update_yaxes(title_text="duty", row=4, col=1, secondary_y=True)
    fig.update_xaxes(title_text="Local time", row=4, col=1)
    fig.write_html(str(output_path), include_plotlyjs="cdn")


def main() -> None:
    parser = argparse.ArgumentParser(description="Train residual RF on top of thermal-mass physics")
    parser.add_argument("--data-path", default="tests_thermal/data/test_data_prepared.csv")
    parser.add_argument("--physics-report-dir", default="tests_thermal/reports/thermal_mass_physics_sundir_20260519_final")
    parser.add_argument("--report-dir", default="tests_thermal/reports/thermal_mass_physics_residual_rf")
    parser.add_argument("--n-estimators", type=int, default=500)
    parser.add_argument("--min-samples-leaf", type=int, default=4)
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    data_path = Path(args.data_path)
    physics_report_dir = Path(args.physics_report_dir)
    report_dir = Path(args.report_dir)
    report_dir.mkdir(parents=True, exist_ok=True)

    physics_payload = json.loads((physics_report_dir / "thermal_mass_physics_metrics.json").read_text(encoding="utf-8"))
    config = physics_payload["config"]
    params = np.array([physics_payload["params"][name] for name in tm.PARAM_NAMES], dtype=float)

    target_cols = [c.strip() for c in config["target_cols"].split(",") if c.strip()]
    opts = SearchOptions(
        lookahead=int(config["lookahead"]),
        feature_level=config["feature_level"],
        target_cols=target_cols,
        latitude=float(config["latitude"]),
        longitude=float(config["longitude"]),
        seed=int(config.get("seed", args.seed)),
    )
    X_raw, y_raw, _, _, _ = _prepare_features(data_path, opts=opts)
    aligned_index = _build_aligned_index(data_path, opts)
    X_seq, y_seq = create_sequences(
        X_raw,
        y_raw,
        lookback=int(config["input_window"]),
        lookahead=int(config["lookahead"]),
    )
    X_train, _, X_val, _, X_test, _ = split_sequences(X_seq, y_seq)
    n_train, n_val = len(X_train), len(X_val)
    n_seq = len(X_seq)
    seq_start_ts = aligned_index[int(config["input_window"]) : int(config["input_window"]) + n_seq].to_numpy()
    train_ts = seq_start_ts[:n_train]
    val_ts = seq_start_ts[n_train : n_train + n_val]
    train_val_ts = seq_start_ts[: n_train + n_val]
    test_ts = seq_start_ts[n_train + n_val :]

    if config.get("holdout_split") == "val":
        fit_ts = train_ts
        eval_ts = val_ts
    else:
        fit_ts = train_val_ts if config.get("fit_on") == "train_val" else train_ts
        eval_ts = test_ts

    raw_df = _load_raw_df(data_path)
    df_fit = _slice(raw_df, fit_ts)
    df_eval = _slice(raw_df, eval_ts)
    df_history = raw_df.loc[raw_df.index < df_eval.index[0]].copy()

    fit_inputs = _prepare_inputs(df_fit, config)
    eval_inputs = _prepare_inputs(df_eval, config)
    history_inputs = _prepare_inputs(df_history, config)
    dt_h = tm._infer_timestep_hours(raw_df.index)

    fit_sim = _simulate_segmented_full(
        fit_inputs,
        params,
        dt_h=dt_h,
        segment_len=int(config["fit_segment_len"]),
    )
    initial_air, initial_mass, initial_q_emit = tm._estimate_initial_states(
        history_inputs,
        params,
        dt_h=dt_h,
        warmup_steps=int(config["state_warmup_steps"]),
    )
    initial_air = tm._latest_before(raw_df, df_eval.index[0], "room_temp", initial_air)
    eval_sim = tm._simulate_open_loop(
        eval_inputs,
        params,
        dt_h=dt_h,
        initial_air=initial_air,
        initial_mass=initial_mass,
        initial_q_emit=initial_q_emit,
    )

    train_room_state = tm._observed_previous_room(df_fit)
    train_q_state = tm._q_emit_from_room_state(fit_inputs, train_room_state, params, dt_h=dt_h)
    X_power_train = tm._power_features(fit_inputs, train_room_state, train_q_state)
    elec_model = tm._fit_power_head(X_power_train, fit_inputs.electric, alpha=float(config["power_ridge_alpha"]))
    gas_model = tm._fit_power_head(X_power_train, fit_inputs.gas, alpha=float(config["gas_ridge_alpha"]))

    X_power_fit_sim = tm._power_features(fit_inputs, fit_sim.air_before, fit_sim.q_emit)
    X_power_eval = tm._power_features(eval_inputs, eval_sim.air_before, eval_sim.q_emit)
    fit_base_electric = np.clip(elec_model.predict(X_power_fit_sim), 0.0, None)
    fit_base_gas = np.clip(gas_model.predict(X_power_fit_sim), 0.0, None)
    eval_base_electric = np.clip(elec_model.predict(X_power_eval), 0.0, None)
    eval_base_gas = np.clip(gas_model.predict(X_power_eval), 0.0, None)
    fit_base_gas[fit_inputs.outdoor > float(config["gas_cutoff_temp"])] = 0.0
    eval_base_gas[eval_inputs.outdoor > float(config["gas_cutoff_temp"])] = 0.0

    X_res_fit = _residual_features(
        fit_inputs,
        fit_sim,
        base_electric=fit_base_electric,
        base_gas=fit_base_gas,
    )
    X_res_eval = _residual_features(
        eval_inputs,
        eval_sim,
        base_electric=eval_base_electric,
        base_gas=eval_base_gas,
    )

    rf_room = _fit_rf(
        X_res_fit,
        fit_inputs.room - fit_sim.room,
        seed=args.seed + 1,
        n_estimators=args.n_estimators,
        min_samples_leaf=args.min_samples_leaf,
    )
    rf_electric = _fit_rf(
        X_res_fit,
        fit_inputs.electric - fit_base_electric,
        seed=args.seed + 2,
        n_estimators=args.n_estimators,
        min_samples_leaf=args.min_samples_leaf,
    )
    rf_gas = _fit_rf(
        X_res_fit,
        fit_inputs.gas - fit_base_gas,
        seed=args.seed + 3,
        n_estimators=args.n_estimators,
        min_samples_leaf=args.min_samples_leaf,
    )

    pred_room = eval_sim.room + rf_room.predict(X_res_eval.to_numpy(dtype=float))
    pred_electric = np.clip(eval_base_electric + rf_electric.predict(X_res_eval.to_numpy(dtype=float)), 0.0, None)
    pred_gas = np.clip(eval_base_gas + rf_gas.predict(X_res_eval.to_numpy(dtype=float)), 0.0, None)
    pred_gas[eval_inputs.outdoor > float(config["gas_cutoff_temp"])] = 0.0

    metrics = {
        "ThermalMassPhysics": {
            "room_temp": _metrics(eval_inputs.room, eval_sim.room),
            "electric_power": _metrics(eval_inputs.electric, eval_base_electric),
            "gas_consumption": _metrics(eval_inputs.gas, eval_base_gas),
        },
        "ThermalMassResidualRF": {
            "room_temp": _metrics(eval_inputs.room, pred_room),
            "electric_power": _metrics(eval_inputs.electric, pred_electric),
            "gas_consumption": _metrics(eval_inputs.gas, pred_gas),
        },
    }

    pred_df = pd.DataFrame(
        {
            "timestamp": eval_inputs.index,
            "true_room_temp": eval_inputs.room,
            "physics_room_temp": eval_sim.room,
            "residual_rf_room_temp": pred_room,
            "true_electric_power": eval_inputs.electric,
            "physics_electric_power": eval_base_electric,
            "residual_rf_electric_power": pred_electric,
            "true_gas_consumption": eval_inputs.gas,
            "physics_gas_consumption": eval_base_gas,
            "residual_rf_gas_consumption": pred_gas,
            "heatpump_duty": eval_inputs.heatpump_duty,
            "outdoor_temp": eval_inputs.outdoor,
            "supply_temp": eval_inputs.supply,
            "q_solar": eval_inputs.q_solar,
            "t_mass": eval_sim.mass,
            "q_emit": eval_sim.q_emit,
        }
    )
    pred_df.to_csv(report_dir / "thermal_mass_residual_rf_predictions.csv", index=False)

    rows = []
    for model, by_target in metrics.items():
        for target, vals in by_target.items():
            rows.append({"model": model, "target": target, **vals})
    pd.DataFrame(rows).to_csv(report_dir / "thermal_mass_residual_rf_metrics.csv", index=False)
    (report_dir / "thermal_mass_residual_rf_metrics.json").write_text(
        json.dumps(
            {
                "metrics": metrics,
                "physics_report_dir": str(physics_report_dir),
                "config": {
                    "n_estimators": args.n_estimators,
                    "min_samples_leaf": args.min_samples_leaf,
                    "seed": args.seed,
                    "residual_feature_cols": list(X_res_fit.columns),
                    "n_fit": int(len(X_res_fit)),
                    "n_eval": int(len(X_res_eval)),
                    "holdout_split": config.get("holdout_split"),
                    "fit_on": config.get("fit_on"),
                },
            },
            indent=2,
        ),
        encoding="utf-8",
    )
    _plot(pred_df, metrics, report_dir / "thermal_mass_residual_rf_plot.html")
    print(json.dumps(metrics, indent=2), flush=True)


if __name__ == "__main__":
    main()
